version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
    restart: unless-stopped
    working_dir: /app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Uncomment to add a database in the future
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=optionclass
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
